# Generated by Django 5.0.8 on 2024-09-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0002_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viveros', to='vivero.finca')),
            ],
        ),
    ]
