# Generated by Django 5.0.8 on 2024-09-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0003_vivero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('vivero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='vivero.vivero')),
            ],
        ),
    ]
