# Generated by Django 5.0.8 on 2024-09-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vivero', '0006_productocontrolfertilizante_productocontrolplaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborProductoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vivero.labor')),
            ],
        ),
    ]
